package uk.co.unisim.jukebox;

import android.app.Activity;
import android.content.ContentResolver;
import android.content.Intent;
import android.content.UriPermission;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.provider.DocumentsContract;
import androidx.activity.result.ActivityResult;
import com.getcapacitor.JSArray;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.ActivityCallback;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.util.ArrayDeque;

/**
 * The music folder on Android: one the person CHOOSES, and keeps.
 *
 * ⚠️ WHY THIS EXISTS, AND WHY THE iOS ANSWER DOES NOT CARRY OVER. On iOS the app
 * walks its own Documents directory, which two Info.plist keys publish to the
 * Files app. {@code @capacitor/filesystem}'s {@code Directory.Documents} on
 * Android is NOT an app folder at all — it is the phone's shared
 * {@code /storage/emulated/0/Documents}, and under scoped storage (Android 11+)
 * an app can list only the files IT created there. Measured on an Android 15
 * emulator, 2026-09-10: an MP3 put into Documents from outside was invisible
 * to {@code readdir}, which returned only the readme the app had written itself;
 * and {@code /sdcard/Music/<artist>/<album>} listed as EMPTY. So the iOS route
 * compiled, installed, and could never find a single track the user put anywhere.
 *
 * The Storage Access Framework is the answer that needs no permission at all:
 * {@code ACTION_OPEN_DOCUMENT_TREE} lets the person pick a folder (it opens on
 * Music), and {@code takePersistableUriPermission} keeps the grant across
 * restarts and reboots. The tree URI is a plain string, so it persists in
 * IndexedDB exactly like the iOS path does, and the library comes back on
 * launch with nothing to confirm. It also sees the {@code cover.jpg} beside
 * an album, which {@code READ_MEDIA_AUDIO} + MediaStore would not.
 *
 * ⚠️ READING IS NOT DONE HERE. The files come back as {@code content://}
 * document URIs, which {@code Capacitor.convertFileSrc} turns into
 * {@code /_capacitor_content_/…} URLs on Capacitor's local server — the same
 * server, and the same range reads, the iOS build uses. Moving bytes through
 * this plugin would mean base64 across the bridge, which is the out-of-memory
 * crash the header of {@code src/lib/scan.ts} forbids, reached a new way.
 *
 * Registered in {@link MainActivity}, not through {@code capacitor.plugins.json}:
 * that file is regenerated by every {@code npx cap sync} and only lists npm
 * packages, so a class declared there by hand would silently vanish.
 */
@CapacitorPlugin(name = "JukeboxMusicFolder")
public class MusicFolderPlugin extends Plugin {

    private static final String[] COLUMNS = {
        DocumentsContract.Document.COLUMN_DOCUMENT_ID,
        DocumentsContract.Document.COLUMN_DISPLAY_NAME,
        DocumentsContract.Document.COLUMN_MIME_TYPE,
        DocumentsContract.Document.COLUMN_SIZE,
        DocumentsContract.Document.COLUMN_LAST_MODIFIED,
    };

    /** Open the system folder picker, starting in Music. */
    @PluginMethod
    public void pick(PluginCall call) {
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);
        intent.addFlags(
            Intent.FLAG_GRANT_READ_URI_PERMISSION |
            Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION |
            Intent.FLAG_GRANT_PREFIX_URI_PERMISSION
        );
        // A hint, not a restriction: the picker opens in Music and the person can
        // go anywhere else from there. Ignored below API 26.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            intent.putExtra(
                DocumentsContract.EXTRA_INITIAL_URI,
                DocumentsContract.buildDocumentUri("com.android.externalstorage.documents", "primary:Music")
            );
        }
        startActivityForResult(call, intent, "picked");
    }

    @ActivityCallback
    private void picked(PluginCall call, ActivityResult result) {
        if (call == null) return;
        Intent data = result.getData();
        if (result.getResultCode() != Activity.RESULT_OK || data == null || data.getData() == null) {
            // Backing out of the picker is an answer, not a failure.
            JSObject cancelled = new JSObject();
            cancelled.put("cancelled", true);
            call.resolve(cancelled);
            return;
        }
        Uri tree = data.getData();
        try {
            // ⚠️ Without this the grant dies with the process, and the library
            // would need its folder chosen again on every launch — the one thing
            // the native build exists to avoid.
            getContext().getContentResolver().takePersistableUriPermission(tree, Intent.FLAG_GRANT_READ_URI_PERMISSION);
        } catch (SecurityException e) {
            call.reject("Android would not let Universal Jukebox keep access to that folder.", "NOT_PERSISTABLE", e);
            return;
        }
        JSObject ret = new JSObject();
        ret.put("uri", tree.toString());
        ret.put("name", displayName(tree));
        call.resolve(ret);
    }

    /**
     * Every file under a chosen folder, as {@code { path, uri, name, size, mtime }}.
     *
     * ⚠️ Rejects with {@code NO_ACCESS} when the grant has gone — the folder was
     * moved, renamed, deleted, or access was withdrawn in Settings — rather than
     * resolving an empty list. "Your folder is empty" and "I could not look" need
     * different things from the person, and conflating them is how a broken app
     * looks merely unused. A sub-folder that will not open is skipped instead.
     */
    @PluginMethod
    public void walk(final PluginCall call) {
        String uriString = call.getString("uri");
        if (uriString == null || uriString.isEmpty()) {
            call.reject("No music folder has been chosen.", "NO_FOLDER");
            return;
        }
        final Uri tree = Uri.parse(uriString);
        if (!stillGranted(tree)) {
            call.reject("Universal Jukebox no longer has access to that folder.", "NO_ACCESS");
            return;
        }
        // Off the plugin thread: every Capacitor plugin shares one, and a big
        // library is hundreds of provider queries.
        new Thread(
            new Runnable() {
                @Override
                public void run() {
                    try {
                        call.resolve(walkTree(tree));
                    } catch (SecurityException e) {
                        call.reject("Universal Jukebox no longer has access to that folder.", "NO_ACCESS", e);
                    } catch (Exception e) {
                        call.reject("That folder could not be read.", "UNREADABLE", e);
                    }
                }
            },
            "jukebox-walk"
        ).start();
    }

    /** Give back a grant that is no longer used, e.g. after choosing a different folder. */
    @PluginMethod
    public void release(PluginCall call) {
        String uriString = call.getString("uri");
        if (uriString != null && !uriString.isEmpty()) {
            try {
                getContext().getContentResolver().releasePersistableUriPermission(Uri.parse(uriString), Intent.FLAG_GRANT_READ_URI_PERMISSION);
            } catch (Exception ignored) {
                // Nothing held, or already gone: either way there is nothing to give back.
            }
        }
        call.resolve();
    }

    private JSObject walkTree(Uri tree) {
        ContentResolver resolver = getContext().getContentResolver();
        JSArray files = new JSArray();
        // { documentId, path relative to the chosen folder }. Iterative, for the
        // reason `walkHandle` in scan.ts gives: a stack blown halfway loses
        // everything found so far.
        ArrayDeque<String[]> stack = new ArrayDeque<>();
        String rootId = DocumentsContract.getTreeDocumentId(tree);
        stack.push(new String[] { rootId, "" });

        while (!stack.isEmpty()) {
            String[] dir = stack.pop();
            boolean isRoot = dir[0].equals(rootId);
            Cursor cursor;
            try {
                cursor = resolver.query(DocumentsContract.buildChildDocumentsUriUsingTree(tree, dir[0]), COLUMNS, null, null, null);
            } catch (RuntimeException e) {
                if (isRoot) throw e;
                continue;
            }
            if (cursor == null) {
                if (isRoot) throw new IllegalStateException("The folder could not be listed.");
                continue;
            }
            try {
                while (cursor.moveToNext()) {
                    String id = cursor.getString(0);
                    String name = cursor.getString(1);
                    String mime = cursor.getString(2);
                    if (id == null || name == null || skippable(name)) continue;
                    String path = dir[1].isEmpty() ? name : dir[1] + "/" + name;
                    if (DocumentsContract.Document.MIME_TYPE_DIR.equals(mime)) {
                        stack.push(new String[] { id, path });
                        continue;
                    }
                    JSObject entry = new JSObject();
                    entry.put("path", path);
                    entry.put("uri", DocumentsContract.buildDocumentUriUsingTree(tree, id).toString());
                    entry.put("name", name);
                    entry.put("size", cursor.isNull(3) ? 0L : cursor.getLong(3));
                    // ⚠️ 0, never "now", when the provider has none: mtime is part
                    // of `trackKey`, and a fresh value every scan would orphan every
                    // play count and cover fix keyed to the track.
                    entry.put("mtime", cursor.isNull(4) ? 0L : cursor.getLong(4));
                    files.put(entry);
                }
            } finally {
                cursor.close();
            }
        }
        JSObject ret = new JSObject();
        ret.put("files", files);
        return ret;
    }

    /** Mirrors `skippable` in nativeFile.ts — never music, sometimes enormous. */
    private static boolean skippable(String name) {
        return name.startsWith(".") || name.equals("node_modules");
    }

    private boolean stillGranted(Uri tree) {
        for (UriPermission permission : getContext().getContentResolver().getPersistedUriPermissions()) {
            if (permission.isReadPermission() && permission.getUri().equals(tree)) return true;
        }
        return false;
    }

    /** "Music", not "primary:Music" — what the folder is called, for the library's folder list. */
    private String displayName(Uri tree) {
        String docId = DocumentsContract.getTreeDocumentId(tree);
        Cursor cursor = null;
        try {
            cursor = getContext()
                .getContentResolver()
                .query(
                    DocumentsContract.buildDocumentUriUsingTree(tree, docId),
                    new String[] { DocumentsContract.Document.COLUMN_DISPLAY_NAME },
                    null,
                    null,
                    null
                );
            if (cursor != null && cursor.moveToFirst() && !cursor.isNull(0)) return cursor.getString(0);
        } catch (Exception ignored) {
            // Fall through to the id, which is readable enough.
        } finally {
            if (cursor != null) cursor.close();
        }
        int cut = Math.max(docId.lastIndexOf('/'), docId.lastIndexOf(':'));
        return cut >= 0 && cut < docId.length() - 1 ? docId.substring(cut + 1) : docId;
    }
}
